{
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT
 *
 * This file provides an Object Pascal interface to the ExternalObj.tlb type
 * library. The type library defines defines the interface to extensions to the
 * browser control DOM's "external object".
 *
 * The interfaces are declared in ExternalObj.idl
 *
 * This file was generated from ExternalObj.tlb by Borland TLibImp.exe.
 * ExternalObj.tlb was generated from ExternalObj.idl by Microsoft MIDL.exe .
 *
 *
 * ***** BEGIN LICENSE BLOCK *****
 *
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific language governing rights and limitations under the License.
 *
 * The Original Code is IntfExternalObj.pas, autogenerated from ExternalObj.idl.
 *
 * The Initial Developer of the Original Code is Peter Johnson
 * (http://www.delphidabbler.com/).
 *
 * Portions created by the Initial Developer are Copyright (C) 2006-2009 Peter
 * Johnson. All Rights Reserved.
 *
 * ***** END LICENSE BLOCK *****
}


unit IntfExternalObj;

// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// PASTLWTR : 1.2
// File generated on 28/06/2009 20:50:08 from Type Library described below.

// ************************************************************************  //
// Type Lib: ..\Bin\ExternalObj.tlb (1)
// LIBID: {FFAFBDD9-3E9A-408D-8616-167018E2083A}
// LCID: 0
// Helpfile: 
// HelpString: CodeSnip DOM External Object Extender Type Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\system32\stdole2.tlb)
// ************************************************************************ //
// *************************************************************************//
// NOTE:                                                                      
// Items guarded by $IFDEF_LIVE_SERVER_AT_DESIGN_TIME are used by properties  
// which return objects that may need to be explicitly created via a function 
// call prior to any access via the property. These items have been disabled  
// in order to prevent accidental use from within the object inspector. You   
// may enable them by defining LIVE_SERVER_AT_DESIGN_TIME or by selectively   
// removing them from the $IFDEF blocks. However, such items must still be    
// programmatically created via a method of the appropriate CoClass before    
// they can be used.                                                          
{$TYPEDADDRESS OFF} // Unit must be compiled without type-checked pointers. 
{$WARN SYMBOL_PLATFORM OFF}
{$WRITEABLECONST ON}
{$VARPROPSETTER ON}
interface

uses Windows, ActiveX, Classes, Graphics, StdVCL, Variants;
  

// *********************************************************************//
// GUIDS declared in the TypeLibrary. Following prefixes are used:        
//   Type Libraries     : LIBID_xxxx                                      
//   CoClasses          : CLASS_xxxx                                      
//   DISPInterfaces     : DIID_xxxx                                       
//   Non-DISP interfaces: IID_xxxx                                        
// *********************************************************************//
const
  // TypeLibrary Major and minor versions
  ExternalObjMajorVersion = 5;
  ExternalObjMinorVersion = 0;

  LIBID_ExternalObj: TGUID = '{FFAFBDD9-3E9A-408D-8616-167018E2083A}';

  IID_IWBExternal5: TGUID = '{61AB2A0B-0262-49D5-8E6D-43161D5A3C9D}';
type

// *********************************************************************//
// Forward declaration of types defined in TypeLibrary                    
// *********************************************************************//
  IWBExternal5 = interface;
  IWBExternal5Disp = dispinterface;

// *********************************************************************//
// Interface: IWBExternal5
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {61AB2A0B-0262-49D5-8E6D-43161D5A3C9D}
// *********************************************************************//
  IWBExternal5 = interface(IDispatch)
    ['{61AB2A0B-0262-49D5-8E6D-43161D5A3C9D}']
    procedure UpdateDbase; safecall;
    procedure DisplaySnippet(const SnippetName: WideString; UserDefined: WordBool); safecall;
    procedure CompileSnippet; safecall;
    procedure ViewCompilerLog(Ver: SYSINT); safecall;
    procedure ShowHint(const Hint: WideString); safecall;
    procedure ConfigCompilers; safecall;
    procedure ShowTestUnit; safecall;
    procedure EditSnippet(const SnippetName: WideString); safecall;
    procedure Donate; safecall;
  end;

// *********************************************************************//
// DispIntf:  IWBExternal5Disp
// Flags:     (4416) Dual OleAutomation Dispatchable
// GUID:      {61AB2A0B-0262-49D5-8E6D-43161D5A3C9D}
// *********************************************************************//
  IWBExternal5Disp = dispinterface
    ['{61AB2A0B-0262-49D5-8E6D-43161D5A3C9D}']
    procedure UpdateDbase; dispid 101;
    procedure DisplaySnippet(const SnippetName: WideString; UserDefined: WordBool); dispid 102;
    procedure CompileSnippet; dispid 103;
    procedure ViewCompilerLog(Ver: SYSINT); dispid 104;
    procedure ShowHint(const Hint: WideString); dispid 105;
    procedure ConfigCompilers; dispid 106;
    procedure ShowTestUnit; dispid 107;
    procedure EditSnippet(const SnippetName: WideString); dispid 108;
    procedure Donate; dispid 109;
  end;

implementation

uses ComObj;

end.
