{
 * USaveUnitMgr.pas
 *
 * Defines a class that manages generation, previewing and saving of a pascal
 * unit.
 *
 * $Rev$
 * $Date$
 *
 * ***** BEGIN LICENSE BLOCK *****
 *
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific language governing rights and limitations under the License.
 *
 * The Original Code is USaveUnitMgr.pas
 *
 * The Initial Developer of the Original Code is Peter Johnson
 * (http://www.delphidabbler.com/).
 *
 * Portions created by the Initial Developer are Copyright (C) 2006-2010 Peter
 * Johnson. All Rights Reserved.
 *
 * Contributor(s)
 *   NONE
 *
 * ***** END LICENSE BLOCK *****
}


unit USaveUnitMgr;


interface


uses
  // Project
  UBaseObjects, UIStringList, USourceFileInfo, USourceFileOutputMgr, USourceGen,
  USnippets;


type

  {
  TSaveUnitMgr:
    Manages generation, previewing and saving of a Pascal unit to disk.
    Generated file can be a valid Pascal unit, a plain text file, an HTML file
    or a RTF file. The last two files types can optionally be syntax
    highlighted.
  }
  TSaveUnitMgr = class(TSaveSourceMgr)
  strict private
    fSourceGen: TSourceGen;
      {Generates source code unit}
    fUnitName: string;
      {Name of generated unit. Name is based on file when saving unit and has a
      default fixed value when previewing}
    fContainsMainDBSnippets: Boolean;
      {Flag true if unit contains at least one snippet from main database, False
      only if unit is completely user defined}
    function UnitName: string;
      {Gets name of unit to be used in generated code.
        @return Name of unit.
      }
    function CreateHeaderComments: IStringList;
      {Creates and stores header comments to be written to head of unit.
        @return String list containing comments.
      }
  strict protected
    constructor InternalCreate(const Snips: TRoutineList);
      {Class constructor. Sets up object to save a unit containing all snippets
      in a list.
        @param Snips [in] List of snippets to include in unit.
      }
    function GetFileTypeDesc(const FileType: TSourceFileType): string; override;
    function GetDefaultFileName: string; override;
    function GetDlgTitle: string; override;
    function GetDlgHelpKeyword: string; override;
    procedure GenerateSource(const CommentStyle: TCommentStyle;
      out RawSourceCode, DocTitle: string); override;
    procedure CheckFileName(const FileName: string; out NameOK: Boolean;
      out ErrorMessage: string); override;
  public
    destructor Destroy; override;
      {Class destructor. Tears down object.
      }
    class procedure Execute(const Snips: TRoutineList);
      {Gets information from user about name and format of required file and
      saves unit containing specified snippets to disk.
        @param Snips [in] List of snippets to include in unit.
      }
  end;


implementation


uses
  // Delphi
  SysUtils,
  // Project
  UAppInfo, UEncodings, UUtils, Web.UInfo;


resourcestring
  // Dialog box title
  sSaveDlgTitle = 'Save Unit';
  // File filter strings
  sHTMLDesc = 'HTML file';
  sRTFDesc = 'Rich text file';
  sPascalDesc = 'Pascal unit';
  sTextDesc = 'Plain text file';
  // Default file / unit name
  sDefUnitName = 'Snippets';
  // Error message
  sErrorMsg = 'Filename is not valid for a Pascal unit';
  // Unit header comments
  sLicense = 'This unit may be freely distributed and used on the condition '
    + 'that this comment is not removed from the unit.';
  sMainDescription = 'The unit was generated automatically from a '
    + 'selection of source code taken from the Code Snippets Database at %0:s.';
  sDisclaimer = 'The source code contained in this unit is made available on '
    + 'an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or '
    + 'implied. The code is used entirely at your own risk.';
  sGenerated = 'Generated on : %0:s.';
  sGenerator = 'Generated by : %0:s %1:s.';
  sAdvert = 'The latest version of %0:s is available from the %1:s website '
    + 'at %2:s.';
  sUserDescription = 'This unit was generated automatically.';
  // Output document title
  sDocTitle = 'Unit "%0:s" generated by %1:s';


{ TSaveUnitMgr }

procedure TSaveUnitMgr.CheckFileName(const FileName: string;
  out NameOK: Boolean; out ErrorMessage: string);
begin
  NameOK := TSourceGen.IsFileNameValidUnitName(FileName);
  if NameOK then
    fUnitName := TSourceGen.UnitNameFromFileName(FileName)
  else
  begin
    fUnitName := '';
    ErrorMessage := sErrorMsg
  end;
end;

function TSaveUnitMgr.CreateHeaderComments: IStringList;
  {Creates and stores header comments to be written to head of unit.
    @return String list containing comments.
  }
begin
  Result := TIStringList.Create;
  if fContainsMainDBSnippets then
  begin
    // Result used for units that contain at snippet(s) from main database
    Result.Add(sLicense);
    Result.Add('');
    Result.Add(Format(sMainDescription, [TWebInfo.DatabaseURL]));
    Result.Add('');
    Result.Add(sDisclaimer);
    Result.Add('');
    Result.Add(Format(sGenerated, [DateStamp]));
    Result.Add(
      Format(
        sGenerator, [TAppInfo.FullProgramName, TAppInfo.ProgramReleaseInfo]
      )
    );
    Result.Add('');
    Result.Add(
      Format(
        sAdvert,
        [TAppInfo.ProgramName, TAppInfo.CompanyName, TWebInfo.ProgramHomeURL]
      )
    );
  end
  else
  begin
    // Result used for units that contain only user defined snippets
    Result.Add(sUserDescription);
    Result.Add('');
    Result.Add(Format(sGenerated, [DateStamp]));
    Result.Add(
      Format(
        sGenerator, [TAppInfo.FullProgramName, TAppInfo.ProgramReleaseInfo]
      )
    );
  end;
end;

destructor TSaveUnitMgr.Destroy;
  {Class destructor. Tears down object.
  }
begin
  fSourceGen.Free;
  inherited;
end;

class procedure TSaveUnitMgr.Execute(const Snips: TRoutineList);
  {Gets information from user about name and format of required file and saves
  unit containing specified snippets to disk.
    @param Snips [in] List of snippets to include in unit.
  }
begin
  with InternalCreate(Snips) do
    try
      DoExecute;
    finally
      Free;
    end;
end;

procedure TSaveUnitMgr.GenerateSource(const CommentStyle: TCommentStyle;
  out RawSourceCode, DocTitle: string);
begin
  RawSourceCode := fSourceGen.UnitAsString(
    UnitName, CommentStyle, CreateHeaderComments
  );
  DocTitle := Format(sDocTitle, [UnitName, TAppInfo.ProgramName]);
end;

function TSaveUnitMgr.GetDefaultFileName: string;
begin
  Result := sDefUnitName;
end;

function TSaveUnitMgr.GetDlgHelpKeyword: string;
begin
  Result := 'SaveUnitDlg';
end;

function TSaveUnitMgr.GetDlgTitle: string;
begin
  Result := sSaveDlgTitle;
end;

function TSaveUnitMgr.GetFileTypeDesc(const FileType: TSourceFileType): string;
const
  Descriptions: array[TSourceFileType] of string = (
    sTextDesc, sPascalDesc, sHTMLDesc, sRTFDesc
  );
begin
  Result := Descriptions[FileType];
end;

constructor TSaveUnitMgr.InternalCreate(const Snips: TRoutineList);
  {Class constructor. Sets up object to save a unit containing all snippets in a
  list.
    @param Snips [in] List of snippets to include in unit.
  }
var
  Snippet: TRoutine;  // references each snippet in list
begin
  Assert(Assigned(Snips), ClassName + '.InternalCreate: Snips is nil');
  inherited InternalCreate;

  // Create source generator and initialize it with required snippets
  fSourceGen := TSourceGen.Create;
  fSourceGen.IncludeSnippets(Snips);

  // Determine if snippet list contains at least one snippet from main database
  fContainsMainDBSnippets := False;
  for Snippet in Snips do
  begin
    if not Snippet.UserDefined then
    begin
      fContainsMainDBSnippets := True;
      Break;
    end;
  end;
end;

function TSaveUnitMgr.UnitName: string;
  {Gets name of unit to be used in generated code.
    @return Name of unit.
  }
begin
  // If we have valid unit name based on file, use it, otherwise use default
  if fUnitName <> '' then
    Result := fUnitName
  else
    Result := sDefUnitName;
end;

end.

